import me.modmuss50.mpp.ReleaseType

plugins {
	id 'fabric-loom' version '1.8-SNAPSHOT'
	id "me.modmuss50.mod-publish-plugin" version "0.8.3"
}

JavaLanguageVersion JAVA_VERSION = JavaLanguageVersion.of(java_version)

base {
	archivesName = mod_id + "-" + mod_version + "+" + minecraft_version + "-fabric"
}

repositories {
	maven {
		name = 'ParchmentMC'
		url = 'https://maven.parchmentmc.org'
	}
}

loom {
	splitEnvironmentSourceSets()

	mods {
		"circumnavigate" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}

	accessWidenerPath = file("src/main/resources/circumnavigate.accesswidener")

	runs {
		client {
			//Used for debug hot-swapping mixins
			//vmArgs("-javaagent", "\"sponge-mixin:x.x.x.jar\"")

			//Used for debug hot-swapping fields, methods, and classes
			//vmArg("-XX:+AllowEnhancedClassRedefinition")

            vmArgs("-Denv=dev")

			programArgs("--width", "1280", "--height", "720", "--username", "dev")
		}
	}
}

dependencies {
	//Minecraft
	minecraft "com.mojang:minecraft:${minecraft_version}"

	//Mojang mappings
	mappings loom.layered() {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${parchment_version}@zip")
    }

	//Fabric Loader
	modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"

	//Fabric API
	modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"

	//Java preprocessor
	annotationProcessor "systems.manifold:manifold-preprocessor:${manifold_preprocessor_version}"
}

processResources {
	filesMatching("fabric.mod.json") {
		expand (
				"mod_id": mod_id,
				"mod_name": mod_name,
				"mod_version": mod_version,
				"mc_version": minecraft_version,
				"fabric_loader_version": fabric_loader_version,
				"java_version": java_version,
				"fabric_api_version": fabric_api_version
		)
	}
}

publishMods {
	file = remapJar.archiveFile
	displayName = mod_version + "+" + minecraft_version + "-fabric"
	//changelog = file("CHANGELOG.md").getText()
	version = mod_version
	type = ReleaseType.of(mod_stage)
	modLoaders.add("fabric")

	modrinth {
		accessToken = providers.environmentVariable("MODRINTH_TOKEN")
		projectId = "hyNSf1Ht"
		minecraftVersions.add(minecraft_version)

		requires("fabric-api")
	}

	curseforge {
		accessToken = providers.environmentVariable("CURSEFORGE_TOKEN")
		projectId = "990175"
		minecraftVersions.add(minecraft_version)

		clientRequired = false
		serverRequired = true

		requires("fabric-api")
	}

	github {
		accessToken = providers.environmentVariable("GITHUB_TOKEN")
		repository = "FamroFexl/Circumnavigate"
		commitish = "develop"
		tagName = mod_version + (mod_stage != "alpha" || mod_stage != "beta") ? "" : "-" + mod_stage
	}

}

tasks.withType(JavaCompile).configureEach {
	it.options.encoding = 'UTF-8'
	it.options.release = JAVA_VERSION.asInt()

	//For enabling java preprocessor on build
	it.options.compilerArgs += ['-Xplugin:Manifold']
}

java {
	//withSourcesJar()

	sourceCompatibility = JAVA_VERSION
	targetCompatibility = JAVA_VERSION
}

jar {
	from("LICENSE") {
		rename { "${it}_${project.base.archivesName.get()}"}
	}

	manifest {
		attributes([
				'Specification-Title'     : "Fabric Loader",
				'Specification-Vendor'    : "FabricMC",
				'Specification-Version'   : fabric_loader_version,
				'Implementation-Title'    : mod_name,
				'Implementation-Version'  : mod_version,
				'Implementation-Vendor'   : "Famro Fexl",
				'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
				'Timestamp'               : System.currentTimeMillis(),
				'Built-On-Java'           : "${System.getProperty('java.vm.version')} (${System.getProperty('java.vm.vendor')})",
				'Built-On-Minecraft'      : minecraft_version
		])
	}
}