name: Feature request
description: Request a feature
title: "[Feature Request]: "
labels: "enhancement"
body:
  - type: textarea
    attributes:
      label: Suggestion
      description: A clear and concise description of what you would like to add.
    validations:
      required: true