#Java
java_version = 21

#Minecraft
minecraft_version=1.21.1
parchment_version = 1.21.1:2024.11.17

#Fabric
fabric_loader_version=0.18.6
fabric_api_version=0.116.10+1.21.1

sodium_version = mc1.21.1-0.6.13-fabric

#Iris
iris_shaders_version = 1.8.8+1.21.1-fabric
antlr4_runtime_version = 4.13.1
glsl_transformer_version = 2.0.1
anarres_jcpp_version = 1.4.14